# Generated by Django 3.0.6 on 2022-03-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_cvv',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_expiry',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_name',
        ),
    ]
