# Generated by Django 3.0.6 on 2022-03-26 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funs', '0002_auto_20220326_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='onCard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funs.CardType'),
        ),
    ]
