# Generated by Django 3.0.6 on 2022-03-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funs', '0003_auto_20220326_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='offerDetails',
        ),
        migrations.AddField(
            model_name='offer',
            name='maxOrder',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='minOrder',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offerPercentage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offerValidUpto',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerImage',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerLink',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offerPrice',
            field=models.FloatField(null=True),
        ),
    ]
