# Generated by Django 3.2.5 on 2022-03-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funs', '0005_auto_20220326_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerDescription',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
