# Generated by Django 3.2.5 on 2022-03-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funs', '0006_alter_offer_offerdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerImage',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
